# Generated by Django 3.0.6 on 2020-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunext_paypal_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypal',
            name='address_status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='paypal',
            name='item_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='paypal',
            name='mc_currency',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='paypal',
            name='notify_version',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='paypal',
            name='payer_id',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='paypal',
            name='payment_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='paypal',
            name='payment_gross',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='paypal',
            name='payment_status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='paypal',
            name='protection_eligibility',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='paypal',
            name='receiver_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='paypal',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='paypal',
            name='txn_checkout',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='paypal',
            name='verify_sign',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='ipn_notification',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
