# Generated by Django 2.2.14 on 2020-08-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edunext_paypal_service', '0002_auto_20200803_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypal',
            old_name='txn_checkout',
            new_name='txn_type',
        ),
        migrations.RemoveField(
            model_name='paypal',
            name='ipn_notification',
        ),
    ]
