# Generated by Django 2.2.14 on 2020-08-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunext_paypal_service', '0003_auto_20200803_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
