# Generated by Django 2.2.14 on 2020-08-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunext_paypal_service', '0004_auto_20200803_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal',
            name='payment_date',
            field=models.CharField(max_length=30),
        ),
    ]
