# Generated by Django 3.1 on 2020-08-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunext_paypal_service', '0006_auto_20200804_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal',
            name='payment_gross',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
