# Generated by Django 3.1 on 2020-08-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunext_paypal_service', '0009_auto_20200804_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal',
            name='payment_date',
            field=models.CharField(max_length=30),
        ),
    ]
