# Generated by Django 3.1 on 2020-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunext_paypal_service', '0010_auto_20200804_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal',
            name='notify_version',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
